config/routes.rb
LhdCharts::Application.routes.draw do
  resources :lhd_metrics
  resources :metrics
  resources :lhds
  resources :charts

  root 'charts#index'
end

app/models/lhd.rb
class Lhd < ActiveRecord::Base
end

app/models/lhd_metric.rb
class LhdMetric < ActiveRecord::Base
  belongs_to :lhd
  belongs_to :metric

  def self.entries 
    order('metric_id', 'lhd_id')
  end
end

app/models/metric.rb
class Metric < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  # GET /lhd_metrics
  # GET /lhd_metrics.json
  def index
  end
end

app/controllers/lhd_metrics_controller.rb
class LhdMetricsController < ApplicationController
  before_action :set_lhd_metric, only: [:show, :edit, :update, :destroy]

  # GET /lhd_metrics
  # GET /lhd_metrics.json
  def index
    if params.key? :metric_id
      @lhd_metrics = LhdMetric.where(metric_id: params[:metric_id]).includes(:lhd).entries
    else
      @lhd_metrics = LhdMetric.includes(:lhd).entries
    end
  end

  # GET /lhd_metrics/1
  # GET /lhd_metrics/1.json
  def show
  end

  # GET /lhd_metrics/new
  def new
    @lhd_metric = LhdMetric.new
  end

  # GET /lhd_metrics/1/edit
  def edit
  end

  # POST /lhd_metrics
  # POST /lhd_metrics.json
  def create
    @lhd_metric = LhdMetric.new(lhd_metric_params)

    respond_to do |format|
      if @lhd_metric.save
        format.html { redirect_to @lhd_metric, notice: 'Lhd metric was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lhd_metric }
      else
        format.html { render action: 'new' }
        format.json { render json: @lhd_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lhd_metrics/1
  # PATCH/PUT /lhd_metrics/1.json
  def update
    respond_to do |format|
      if @lhd_metric.update(lhd_metric_params)
        format.html { redirect_to @lhd_metric, notice: 'Lhd metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lhd_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lhd_metrics/1
  # DELETE /lhd_metrics/1.json
  def destroy
    @lhd_metric.destroy
    respond_to do |format|
      format.html { redirect_to lhd_metrics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lhd_metric
      @lhd_metric = LhdMetric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lhd_metric_params
      params.require(:lhd_metric).permit(:percentage, :value, :lhd_id, :metric_id)
    end
end

app/controllers/lhds_controller.rb
class LhdsController < ApplicationController
  before_action :set_lhd, only: [:show, :edit, :update, :destroy]

  # GET /lhds
  # GET /lhds.json
  def index
    @lhds = Lhd.all
  end

  # GET /lhds/1
  # GET /lhds/1.json
  def show
  end

  # GET /lhds/new
  def new
    @lhd = Lhd.new
  end

  # GET /lhds/1/edit
  def edit
  end

  # POST /lhds
  # POST /lhds.json
  def create
    @lhd = Lhd.new(lhd_params)

    respond_to do |format|
      if @lhd.save
        format.html { redirect_to @lhd, notice: 'Lhd was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lhd }
      else
        format.html { render action: 'new' }
        format.json { render json: @lhd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lhds/1
  # PATCH/PUT /lhds/1.json
  def update
    respond_to do |format|
      if @lhd.update(lhd_params)
        format.html { redirect_to @lhd, notice: 'Lhd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lhd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lhds/1
  # DELETE /lhds/1.json
  def destroy
    @lhd.destroy
    respond_to do |format|
      format.html { redirect_to lhds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lhd
      @lhd = Lhd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lhd_params
      params.require(:lhd).permit(:name, :long_name)
    end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = Metric.all
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @metric = Metric.new
  end

  # GET /metrics/1/edit
  def edit
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)

    respond_to do |format|
      if @metric.save
        format.html { redirect_to @metric, notice: 'Metric was successfully created.' }
        format.json { render action: 'show', status: :created, location: @metric }
      else
        format.html { render action: 'new' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to @metric, notice: 'Metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to metrics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric
      @metric = Metric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_params
      params.require(:metric).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lhd_metrics_helper.rb
module LhdMetricsHelper
end

app/helpers/lhds_helper.rb
module LhdsHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/charts/index.html.erb
<div ng-controller="ChartsCtrl">

  <ul class="metric-menu">
    <li ng-model="metric_id"
        ng-class="{selected: isSelected(metric.id)}" 
        ng-repeat="metric in metrics" 
        ng-click="selectMetric(metric.id)">
      {{metric.name}}
    </li>
  </ul>

  <div class="row">
    <div class="col-md-6">

      <bar-chart 
        data="metric_data" 
        selected="selectLhdMetric(args)">
      </bar-chart>

      <div class="panel-info">
        <div class="heading">&nbsp;{{lhd_metric.lhd_name}}</div>
        <div class="body">
        <dl>
          <dt>Value</dt>
            <dd>$ {{lhd_metric.value}} million</dd>
          <dt>Percentage</dt>
            <dd>{{lhd_metric.percentage}} %</dd>
        </dl>
        </div>
      </div>

    </div>

    <div class="col-md-6">
      <map-chart
        data="lhds" 
        selected="selectLhd(args)"
        id="lhd-map">
      </map-chart>
    </div>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="lhd">
<head>
  <title>Lhd Charts</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="app-nav-bar" role="navigation">
  <div class="navbar-header">
    <button type="button" class="app-navbar-toggle" data-toggle="collapse" data-target=".app-navbar-menu">
      <i class="icon-label"></i>
    </button>
    <%= link_to root_path, class: 'app-navbar-brand' do %>
      <i class="icon-logo"></i>
    <% end %>
  </div>

  <div class="app-navbar-menu">
    <ul>
      <li><%= link_to "LHDs", lhds_path %></li>
      <li><%= link_to "Metrics", metrics_path %></li>
      <li><%= link_to "LHD Metrics", lhd_metrics_path %></li>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/lhd_metrics/_form.html.erb
<%= form_for(@lhd_metric) do |f| %>
  <% if @lhd_metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lhd_metric.errors.count, "error") %> prohibited this lhd_metric from being saved:</h2>

      <ul>
      <% @lhd_metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br>
    <%= f.text_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :lhd %><br>
    <%= f.text_field :lhd %>
  </div>
  <div class="field">
    <%= f.label :metric %><br>
    <%= f.text_field :metric %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lhd_metrics/edit.html.erb
<h1>Editing lhd_metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @lhd_metric %> |
<%= link_to 'Back', lhd_metrics_path %>

app/views/lhd_metrics/index.html.erb
<h1>LHD Metrics</h1>
<div ng-controller="LhdMetricListCtrl" class="lhd-metrics">
  <table>
    <thead>
      <tr>
        <th class="lm-metric">Metric</th>
        <th class="lm-lhd">LHD</th>
        <th class="lm-percentage">Percentage</th>
        <th class="lm-value">Value <div class="subtitle">(In Millions)</div></th>
        <th class="row-actions"></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="lm in lhdMetrics" ng-class="{editing: editing, error: error}" ng-controller="LhdMetricCtrl" ng-init="init(lm)">
        <td>
          <select 
            class="lm-metric" 
            ng-model="lm.metric_id" 
            ng-options="metric.id as metric.name for metric in metrics">
          </select>
        </td>
        <td>
          <select 
            class="lm-lhd"  
            ng-model="lm.lhd_id" 
            ng-options="lhd.id as lhd.name for lhd in lhds">
          </select>
        </td>
        <td>
          <input class="lm-percentage" ng-model="lm.percentage">
        </td>
        <td>
          <input class="lm-value" ng-model="lm.value">
        </td>
        <td>
          <div class="app-btns row-actions">
            <button ng-show="editing" ng-click="save()" class="btn">Save</button>
            <button ng-click="delete(lm)" class="btn">Delete</button>
          </div>
        </td>
        <td>
          <div ng-show="error">
            {{error}}
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <button ng-click="add()" class="btn-add">New</button>
</div>

app/views/lhd_metrics/new.html.erb
<h1>New lhd_metric</h1>

<%= render 'form' %>

<%= link_to 'Back', lhd_metrics_path %>

app/views/lhd_metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @lhd_metric.value %>
</p>

<p>
  <strong>Lhd:</strong>
  <%= @lhd_metric.lhd %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @lhd_metric.metric %>
</p>

<%= link_to 'Edit', edit_lhd_metric_path(@lhd_metric) %> |
<%= link_to 'Back', lhd_metrics_path %>

app/views/lhds/_form.html.erb
<%= form_for(@lhd) do |f| %>
  <% if @lhd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lhd.errors.count, "error") %> prohibited this lhd from being saved:</h2>

      <ul>
      <% @lhd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :long_name %><br>
    <%= f.text_field :long_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lhds/edit.html.erb
<h1>Editing lhd</h1>

<%= render 'form' %>

<%= link_to 'Show', @lhd %> |
<%= link_to 'Back', lhds_path %>

app/views/lhds/index.html.erb
<h1>LHDs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lhds.each do |lhd| %>
      <tr>
        <td><%= lhd.name %></td>
        <td><%= link_to 'Show', lhd %> - 
        <%= link_to 'Edit', edit_lhd_path(lhd) %> - 
        <%= link_to 'Destroy', lhd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lhd', new_lhd_path %>

app/views/lhds/new.html.erb
<h1>New lhd</h1>

<%= render 'form' %>

<%= link_to 'Back', lhds_path %>

app/views/lhds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lhd.name %>
  <strong>Long Name:</strong>
  <%= @lhd.long_name %>
</p>

<%= link_to 'Edit', edit_lhd_path(@lhd) %> |
<%= link_to 'Back', lhds_path %>

app/views/metrics/_form.html.erb
<%= form_for(@metric) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metrics/edit.html.erb
<h1>Editing metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

app/views/metrics/index.html.erb
<h1>Metrics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= metric.name %></td>
        <td><%= metric.description %></td>
        <td><%= link_to 'Show', metric %> - 
        <%= link_to 'Edit', edit_metric_path(metric) %> - 
        <%= link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metric', new_metric_path %>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

<%= link_to 'Back', metrics_path %>

app/views/metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metric.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @metric.description %>
</p>

<%= link_to 'Edit', edit_metric_path(@metric) %> |
<%= link_to 'Back', metrics_path %>